"""
Standardized animal color and hatch-pattern mapping for stacked preference plots.

Ensures every animal always gets the same (color, hatch) combination across all
model sizes, seeds, and experiment variants so plots are easy to compare.

The mapping is loaded from ``outputs/animal_style_map.json`` which is generated
by ``src.build_style_map``.  If the file does not exist a warning is emitted
and a deterministic hash fallback is used (run the build script first).
"""

from __future__ import annotations

import json
import warnings
from pathlib import Path

# ---------------------------------------------------------------------------
# 10 visually-distinct base colors (hand-picked for contrast on white bg)
# ---------------------------------------------------------------------------
_BASE_COLORS: list[str] = [
    "#1f77b4",  # blue
    "#ff7f0e",  # orange
    "#2ca02c",  # green
    "#d62728",  # red
    "#9467bd",  # purple
    "#8c564b",  # brown
    "#e377c2",  # pink
    "#17becf",  # cyan
    "#bcbd22",  # olive/yellow-green
    "#7f7f7f",  # gray
]

# ---------------------------------------------------------------------------
# Hatch patterns cycled when we exceed 10 animals
# ---------------------------------------------------------------------------
_HATCH_CYCLE: list[str] = [
    "",      # solid fill  (animals  1-10)
    "//",    # forward slash (animals 11-20)
    "\\\\",  # backslash    (animals 21-30)
    "xx",    # cross-hatch  (animals 31-40)
    "..",    # dots         (animals 41-50)
]

# ---------------------------------------------------------------------------
# Load the pre-built style map from outputs/animal_style_map.json
# Generated by: uv run python -m src.build_style_map
# ---------------------------------------------------------------------------
_STYLE_MAP_PATH = Path("outputs/animal_style_map.json")

ANIMAL_STYLE_MAP: dict[str, tuple[str, str]] = {}

if _STYLE_MAP_PATH.exists():
    with open(_STYLE_MAP_PATH) as _f:
        _raw: dict[str, list[str]] = json.load(_f)
    for _name, (_color, _hatch) in _raw.items():
        ANIMAL_STYLE_MAP[_name] = (_color, _hatch)
else:
    warnings.warn(
        f"Style map not found at {_STYLE_MAP_PATH}. "
        "Run `uv run python -m src.build_style_map` to generate it. "
        "Using hash fallback for all animals.",
        stacklevel=1,
    )


# ---------------------------------------------------------------------------
# Public helpers
# ---------------------------------------------------------------------------

def get_animal_style(name: str) -> tuple[str, str]:
    """Return ``(color_hex, hatch_pattern)`` for *name*.

    Falls back deterministically for unknown animals so the same name always
    gets the same style.
    """
    key = name.lower().strip()
    if key in ANIMAL_STYLE_MAP:
        return ANIMAL_STYLE_MAP[key]

    # Also check original casing (for "Other")
    if name in ANIMAL_STYLE_MAP:
        return ANIMAL_STYLE_MAP[name]

    # Deterministic fallback for truly unknown animals
    h = hash(key) % (len(_BASE_COLORS) * len(_HATCH_CYCLE))
    color = _BASE_COLORS[h % len(_BASE_COLORS)]
    hatch = _HATCH_CYCLE[h // len(_BASE_COLORS)]
    # Cache so repeated calls are consistent within a session
    ANIMAL_STYLE_MAP[key] = (color, hatch)
    return color, hatch


def get_animal_styles(animal_list: list[str]) -> list[tuple[str, str]]:
    """Return a list of ``(color, hatch)`` tuples, one per animal."""
    return [get_animal_style(a) for a in animal_list]
